# Generated by Django 4.1.2 on 2022-10-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elmodel',
            name='duedate',
        ),
        migrations.RemoveField(
            model_name='newword',
            name='date',
        ),
    ]
