# Generated by Django 4.1.2 on 2022-11-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elapp', '0002_remove_elmodel_duedate_remove_newword_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elmodel',
            name='priority',
            field=models.CharField(choices=[('danger', '頻出'), ('info', '重要'), ('success', '基本')], max_length=50),
        ),
        migrations.AlterField(
            model_name='newword',
            name='priority',
            field=models.CharField(choices=[('danger', '頻出'), ('info', '重要'), ('success', '基本')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newword',
            name='useful',
            field=models.PositiveIntegerField(default=1, verbose_name='the number of access'),
        ),
    ]
